### ISSUE TITLE
Impresion de cheques

### ISSUE THREAD

**Issue by raponte25** [eneldoserrata/quirofanos#14]
El cliente quiere poder imprimir cheques desde la instancia.

**Comment by eneldoserrata** [comment]
@raponte25 creada plantilla de cheque en el diario ajustar valores segun imagen
![Screen Shot 2018-04-05 at 5.04.11 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ab4bf61759d7000115d3d3f/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454f66b7191a37df1122f4f5e5e5ecc3c4a4356bcbbd671f3e57862804e0ebc836b0d75c23511a9bed04ebf01ba21d948d6e3be8a4ed2f42f67b6d5db1063474f4dcbed5727a19141c95df449e84b57a01b3363e77f2431.png)

**Comment by gervacio24** [comment]
Cuando se va a imprimir el cheque sale el siguiente error, favor revisar:

![Screenshot-2018-4-6 SUPP OUT 2018 0012 - Odoo(1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5abb8b6868c7e60011dacf56/125516c66e82c728ace21e0d46db978826878dba87e6ab0ef60da1cc64126a256937961b40c5cc1d8b0229515e575eac41595d54e1e9f67ff9e92471934e17ff912f002e936e55beb2901aee53bc728a4b8db6b98c1e91e83d25e6d9881c6b1c051a9be34f77f1c71f9705af01b40f47ae01376aec77337e44941a77246a6624a2facd1b.png)

**Comment by eneldoserrata** [comment]
@gervacio24  reproduce el error y copiame el texto hasta el final

**Comment by gervacio24** [comment]
Este es el error:



Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/odoo/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/home/odoo/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/home/odoo/odoo/addons/report/models/report.py", line 178, in get_pdf
    html = self.with_context(context).get_html(docids, report_name, data=data)
  File "/home/odoo/odoo/addons/report/models/report.py", line 135, in get_html
    return report_model.render_html(docids, data=data)
  File "/home/odoo/marcos_addons/l10n_do_check_printing/report/print_check.py", line 66, in render_html
    return report_obj.render('l10n_do_check_printing.check_print_report', docargs)
  File "/home/odoo/odoo/addons/report/models/report.py", line 120, in render
    return view_obj.render_template(template, values)
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1043, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/odoo/odoo/addons/website/models/ir_ui_view.py", line 115, in render
    return super(View, self).render(values, engine=engine)
  File "/home/odoo/odoo/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1063, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
    raise e
QWebException: None
Traceback (most recent call last):
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 341, in get_template
    document = options.get('load', self.load)(template, options)
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 81, in load
    template = env['ir.ui.view'].read_template(name)
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 938, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "<decorator-gen-226>", line 2, in get_view_id
  File "/home/odoo/odoo/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo/addons/website/models/ir_ui_view.py", line 87, in get_view_id
    return super(View, self).get_view_id(xml_id)
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 950, in get_view_id
    return self.env['ir.model.data'].xmlid_to_res_id(template, raise_if_not_found=True)
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_model.py", line 1085, in xmlid_to_res_id
    return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_model.py", line 1076, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-5>", line 2, in xmlid_lookup
  File "/home/odoo/odoo/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/odoo/odoo/addons/base/ir/ir_model.py", line 1065, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: {{o.journal_id.check_layout.check_header.id}}

load could not load template
Template: {{o.journal_id.check_layout.check_header.id}}
